<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr Lazaros Gonidis">
<meta name="dcterms.date" content="2025-02-13">

<title>AdvancedStatistics - Confirmatory Factor Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">AdvancedStatistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Confirmatory Factor Analysis</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Dr Lazaros Gonidis </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 13, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="todays-aims" class="level2">
<h2 class="anchored" data-anchor-id="todays-aims">Today’s Aims</h2>
<p>Today we will go through confirmatory factor analysis using lavaan. Our main focus will be lavaan syntax and the interpretation of output for different models and not going through the detailed mathematics behind the <strong>CFA processes.</strong> We will get a chance to talk about the mathematics and more during the next weeks of more intermediate and advanced topics.</p>
</section>
<section id="todays-examples" class="level2">
<h2 class="anchored" data-anchor-id="todays-examples">Today’s examples</h2>
<p>We will be working on the same variables that we generated last week during the <strong>EFA</strong>. We will go through the process of <strong>one factor CFA</strong> and <strong>two factor CFA</strong>.</p>
<p>We specifically explored a model with two factors and overall 6 items, today we will first attempt to confirm a model where <strong>three</strong> items load to latent variable A. <strong>This will be our one-factor CFA</strong>.</p>
<p>In the second part of our workshop we will attempt to confirm a model with two <strong>latent variables A and B</strong>.</p>
</section>
<section id="terminology" class="level2">
<h2 class="anchored" data-anchor-id="terminology">Terminology</h2>
<p>Today we will also be referring back to many of the terms that we have defined in the past.</p>
<ol type="1">
<li>Observed variables</li>
<li>Latent variables</li>
<li>Directional/regression paths</li>
<li>Non-directional paths/covariance/variance</li>
<li>Model parameters</li>
<li>Exogenous, endogenous variables</li>
<li>Measurement and structural model</li>
</ol>
</section>
<section id="we-will-expand-on-terminology-today" class="level2">
<h2 class="anchored" data-anchor-id="we-will-expand-on-terminology-today">We will expand on terminology today</h2>
<ol type="1">
<li><strong>Scale:</strong> latent variables do not have a measurement scale, instead we have to define one for them. To do that we need to set an <strong>origin</strong> and a <strong>unit</strong>
<ol type="1">
<li><strong>Origin:</strong> we can set the mean to <strong>0</strong></li>
<li><strong>Unit</strong>
<ol type="1">
<li>Either set the <strong>variance to 1</strong></li>
<li>Or, use the same unit as that of one of the <strong>measured variables ( only 1 item)</strong></li>
</ol></li>
</ol></li>
</ol>
</section>
<section id="notations-in-lavaan-refresher" class="level2">
<h2 class="anchored" data-anchor-id="notations-in-lavaan-refresher">Notations in lavaan (refresher)</h2>
<ul>
<li><p><strong><code>~</code></strong> <strong>predict</strong>, used for regression of observed outcome to observed predictors</p></li>
<li><p><strong><code>=~</code></strong> <strong>indicator</strong>, used for latent variable to observed indicators</p></li>
<li><p><strong><code>~~</code></strong> <strong>covariance</strong></p></li>
<li><p><strong><code>1*</code></strong> <strong>fixes</strong> <strong>parameter</strong> or <strong>loading</strong> to <strong>1</strong></p></li>
<li><p><strong><code>NA*</code></strong> <strong>frees</strong> <strong>parameter</strong> or <strong>loading</strong></p></li>
<li><p><strong><code>~1</code></strong> <strong>intercept</strong> or mean (e.g., <strong><code>x1 ~ 1</code></strong> estimates the mean of variable <strong><code>x1</code></strong>)</p></li>
<li><p><strong><code>a*</code></strong> <strong>defines</strong> the <strong>parameter</strong> ‘a’,</p></li>
</ul>
</section>
<section id="number-of-parameters-refresher" class="level2">
<h2 class="anchored" data-anchor-id="number-of-parameters-refresher">Number of parameters (refresher)</h2>
<p>As mentioned before every <strong>path</strong> or (co)<strong>variance</strong> that has not been fixed to a specific value will have to be estimated</p>
<ol type="1">
<li>Factor loadings</li>
<li>Factor covariances</li>
<li>Factor variances</li>
<li>Error variances</li>
</ol>
</section>
<section id="last-weeks-example" class="level2">
<h2 class="anchored" data-anchor-id="last-weeks-example">Last week’s example</h2>
<p>Last week we generated random data using the 1212 seed. Today we will carry out <strong>CFA</strong> on the same model but using 3131 as a seed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3131</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">### normally distributed factors</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">### these are just to help me set the indicators</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="do">### the f1 and f2 will not be included in the data.frame</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>f1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">250</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>f2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">250</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">### f1 indicators x1 to x3</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> f1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> f1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> f1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="do">### f2 indicators x4 to x6</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> f2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>x5 <span class="ot">&lt;-</span> f2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>x6 <span class="ot">&lt;-</span> f2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">sd=</span><span class="fl">0.15</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="do">### creating the dataframe</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1=</span>x1, <span class="at">x2=</span>x2, <span class="at">x3=</span>x3, <span class="at">x4=</span>x4, <span class="at">x5=</span>x5, <span class="at">x6=</span>x6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="one-factor-cfa" class="level2">
<h2 class="anchored" data-anchor-id="one-factor-cfa">One factor CFA</h2>
<p><img src="onefactor.JPG" class="img-fluid"></p>
</section>
<section id="one-factor-cfa-expanded" class="level2">
<h2 class="anchored" data-anchor-id="one-factor-cfa-expanded">One factor CFA, expanded</h2>
<p><img src="onefactor1.JPG" class="img-fluid"></p>
</section>
<section id="once-factor-cfa-expanded-again" class="level2">
<h2 class="anchored" data-anchor-id="once-factor-cfa-expanded-again">Once factor CFA, expanded (again)</h2>
<p><img src="onefactor2.JPG" class="img-fluid"></p>
</section>
<section id="one-factor-cfa-and-degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="one-factor-cfa-and-degrees-of-freedom">One Factor CFA and degrees of freedom</h2>
<ol type="1">
<li><strong>df &lt; 0</strong>, the model is under-identified</li>
<li><strong>df = 0</strong>, the model is just-identified (also known as saturated), no model fit</li>
<li><strong>df &gt; 0</strong>, over-identified, we can assess model fit</li>
</ol>
<p>Reminder: <strong>df = number of known values - number of parameters to estimate</strong></p>
</section>
<section id="one-factor-cfa-and-degrees-of-freedom-1" class="level2">
<h2 class="anchored" data-anchor-id="one-factor-cfa-and-degrees-of-freedom-1">One Factor CFA and degrees of freedom</h2>
<ol type="1">
<li><p>Total number of parameters (alson knows as “known values”) as previously discussed</p>
<p><span class="math display">\[
p(p+1)/2
\]</span> <span class="math display">\[
3(4)/2=6
\]</span></p></li>
<li><p>Number of parameters to estimate???? (Let us revisit the slide with the model visualisation)</p></li>
</ol>
</section>
<section id="identification-methods" class="level2">
<h2 class="anchored" data-anchor-id="identification-methods">Identification Methods</h2>
<ol type="1">
<li><strong>marker method:</strong> we fix the first loading of each factor to 1 (what does this mean?)</li>
<li><strong>variance standardization method:</strong> we fix the variance of each factor to 1 and we freely estimate all other loadings (what does this mean?)</li>
<li><strong>standardization all method</strong>, standardizes the variance of each factor to 1 but also standardizes the items</li>
</ol>
<p><strong>Note: default lavaan method is the marker method</strong></p>
</section>
<section id="let-us-see-this-example-in-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="let-us-see-this-example-in-lavaan">Let us see this example in lavaan</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>model1.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model1, <span class="at">data =</span> df)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 50 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         6

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  f1 =~                                               
    x1                1.000                           
    x2                0.992    0.014   72.880    0.000
    x3                0.991    0.014   72.206    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .x1                0.019    0.003    6.471    0.000
   .x2                0.023    0.003    7.277    0.000
   .x3                0.023    0.003    7.424    0.000
    f1                0.912    0.083   10.951    0.000</code></pre>
</div>
</div>
</section>
<section id="how-can-we-interpret-this-output" class="level2">
<h2 class="anchored" data-anchor-id="how-can-we-interpret-this-output">How can we interpret this output?</h2>
<ol type="1">
<li>x1 estimate is 1.000 and has no std error, z-value, nor p-value. This is because lavaan uses the <strong>marker method by default</strong>. x1 has been fixed to 1 and is now the scale of our factor 1.</li>
<li>x2 estimate is 0.992. For an increase of <strong>1 unit</strong> in <strong>f1</strong>, x2 increases by 0.992. The 1 unit in f1 is the unit of x1 as this was set to be the scale</li>
<li>.x1 refers to residual variances, hence the . in front of x1</li>
<li>f estimate of 0.912 is the variance of our latent variable (factor)</li>
<li>p-values are just telling us if our estimates are significantly greater than zero</li>
</ol>
<p>But what about intercept???</p>
</section>
<section id="adding-intercept-in-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="adding-intercept-in-lavaan">Adding intercept in lavaan</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>model1.inter <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="st">f1 ~ 1 </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>model1.inter.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model1.inter, <span class="at">data =</span> df)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1.inter.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 50 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        10

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                    NA
  Degrees of freedom                                -1
  P-value (Unknown)                                 NA

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  f1 =~                                               
    x1                1.000                           
    x2                0.992       NA                  
    x3                0.991       NA                  

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    f1                0.000       NA                  
   .x1                0.009       NA                  
   .x2                0.036       NA                  
   .x3                0.014       NA                  

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .x1                0.019       NA                  
   .x2                0.023       NA                  
   .x3                0.023       NA                  
    f1                0.912       NA                  </code></pre>
</div>
</div>
</section>
<section id="what-about-variance-standardization-method" class="level2">
<h2 class="anchored" data-anchor-id="what-about-variance-standardization-method">What about <strong>variance standardization method</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>model1.var <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ NA*x1 + x2 + x3</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="st">f1 ~~ 1*f1 </span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>model1.var.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model1.var, <span class="at">data =</span> df)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1.var.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 30 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         6

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  f1 =~                                               
    x1                0.955    0.044   21.901    0.000
    x2                0.948    0.043   21.811    0.000
    x3                0.946    0.043   21.792    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    f1                1.000                           
   .x1                0.019    0.003    6.471    0.000
   .x2                0.023    0.003    7.277    0.000
   .x3                0.023    0.003    7.424    0.000</code></pre>
</div>
</div>
</section>
<section id="thanks-for-nothing-laz" class="level2">
<h2 class="anchored" data-anchor-id="thanks-for-nothing-laz">Thanks for nothing Laz!</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>model1.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model1, <span class="at">std.lv=</span><span class="cn">TRUE</span>, <span class="at">data =</span> df)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 30 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         6

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  f1 =~                                               
    x1                0.955    0.044   21.901    0.000
    x2                0.948    0.043   21.811    0.000
    x3                0.946    0.043   21.792    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .x1                0.019    0.003    6.471    0.000
   .x2                0.023    0.003    7.277    0.000
   .x3                0.023    0.003    7.424    0.000
    f1                1.000                           </code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Remember this method standardizes our factor, so we will need to speak in terms of standard deviations</p>
<p><strong>x1 estimate of 0.955</strong>: For an increase of 1 standard deviation in <strong>f1</strong>, x1 increases by 0.955</p>
</section>
<section id="and-the-magnificent-standardization-all-walks-in" class="level2">
<h2 class="anchored" data-anchor-id="and-the-magnificent-standardization-all-walks-in">And the magnificent standardization all walks in</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>model1.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model1, <span class="at">data =</span> df)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1.fit, <span class="at">standardized=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 50 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         6

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 =~                                                                 
    x1                1.000                               0.955    0.990
    x2                0.992    0.014   72.880    0.000    0.948    0.988
    x3                0.991    0.014   72.206    0.000    0.946    0.987

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .x1                0.019    0.003    6.471    0.000    0.019    0.020
   .x2                0.023    0.003    7.277    0.000    0.023    0.024
   .x3                0.023    0.003    7.424    0.000    0.023    0.025
    f1                0.912    0.083   10.951    0.000    1.000    1.000</code></pre>
</div>
</div>
</section>
<section id="moving-on-to-model-fit-statistics" class="level2">
<h2 class="anchored" data-anchor-id="moving-on-to-model-fit-statistics">Moving on to Model fit statistics</h2>
<p>As things are now we cannot obtain model fit statistics as <strong>df =0</strong></p>
<p>So our model is just-identified (saturated)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3 + x4</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="st">f2 =~ x5 + x6</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>model2.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model2, <span class="at">data =</span> df)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2.fit, <span class="at">standardized=</span><span class="cn">TRUE</span>, <span class="at">fit.measures=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 48 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        13

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                               812.060
  Degrees of freedom                                 8
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                              3202.055
  Degrees of freedom                                15
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.748
  Tucker-Lewis Index (TLI)                       0.527

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -889.645
  Loglikelihood unrestricted model (H1)       -483.616
                                                      
  Akaike (AIC)                                1805.291
  Bayesian (BIC)                              1851.070
  Sample-size adjusted Bayesian (SABIC)       1809.859

Root Mean Square Error of Approximation:

  RMSEA                                          0.634
  90 Percent confidence interval - lower         0.598
  90 Percent confidence interval - upper         0.671
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.299

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 =~                                                                 
    x1                1.000                               0.955    0.990
    x2                0.992    0.014   72.869    0.000    0.948    0.988
    x3                0.991    0.014   72.277    0.000    0.946    0.987
    x4               -0.090    0.065   -1.397    0.162   -0.086   -0.088
  f2 =~                                                                 
    x5                1.000                               0.960    0.961
    x6                1.028    0.185    5.548    0.000    0.986    1.017

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 ~~                                                                 
    f2               -0.072    0.061   -1.180    0.238   -0.078   -0.078

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .x1                0.019    0.003    6.451    0.000    0.019    0.020
   .x2                0.023    0.003    7.296    0.000    0.023    0.025
   .x3                0.023    0.003    7.424    0.000    0.023    0.025
   .x4                0.947    0.085   11.180    0.000    0.947    0.992
   .x5                0.076    0.166    0.456    0.648    0.076    0.076
   .x6               -0.032    0.175   -0.183    0.855   -0.032   -0.034
    f1                0.912    0.083   10.952    0.000    1.000    1.000
    f2                0.921    0.188    4.903    0.000    1.000    1.000</code></pre>
</div>
</div>
</section>
<section id="what-if-we-make-sure-there-is-no-covariance-between-factors" class="level2">
<h2 class="anchored" data-anchor-id="what-if-we-make-sure-there-is-no-covariance-between-factors">What if we make sure there is no covariance between factors?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model2.nocov <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3 + x4</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="st">f2 =~ x5 + x6</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="st">f1~~0*f2</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>model2.nocov.fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model2.nocov, <span class="at">data =</span> df)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2.nocov.fit, <span class="at">standardized=</span><span class="cn">TRUE</span>, <span class="at">fit.measures=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 52 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        12

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                               813.666
  Degrees of freedom                                 9
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                              3202.055
  Degrees of freedom                                15
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.748
  Tucker-Lewis Index (TLI)                       0.579

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -890.449
  Loglikelihood unrestricted model (H1)       -483.616
                                                      
  Akaike (AIC)                                1804.898
  Bayesian (BIC)                              1847.155
  Sample-size adjusted Bayesian (SABIC)       1809.114

Root Mean Square Error of Approximation:

  RMSEA                                          0.598
  90 Percent confidence interval - lower         0.564
  90 Percent confidence interval - upper         0.633
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.303

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 =~                                                                 
    x1                1.000                               0.955    0.990
    x2                0.992       NA                      0.948    0.988
    x3                0.991       NA                      0.946    0.987
    x4               -0.090       NA                     -0.086   -0.088
  f2 =~                                                                 
    x5                1.000                               0.921    0.923
    x6                1.116       NA                      1.028    1.060

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 ~~                                                                 
    f2                0.000                               0.000    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .x1                0.019       NA                      0.019    0.020
   .x2                0.023       NA                      0.023    0.025
   .x3                0.023       NA                      0.023    0.025
   .x4                0.948       NA                      0.948    0.992
   .x5                0.148       NA                      0.148    0.149
   .x6               -0.115       NA                     -0.115   -0.123
    f1                0.912       NA                      1.000    1.000
    f2                0.848       NA                      1.000    1.000</code></pre>
</div>
</div>
</section>
<section id="can-we-improve-our-model" class="level2">
<h2 class="anchored" data-anchor-id="can-we-improve-our-model">Can we improve our model?</h2>
<p>One way to do that is to look into our model residuals. Model residuals are an <strong>absolute fit index</strong> where we compare our model with th observed data. Generally, you regard <strong>absolute goodness of fit</strong> as the “discrepancy” between our model and the observed data. Higher residuals indicate greater discrepancy.</p>
<p>So how high is bad? We can request either <strong>correlations</strong> or <strong>standardized residuals</strong>.</p>
</section>
<section id="correlations" class="level2">
<h2 class="anchored" data-anchor-id="correlations">Correlations</h2>
<p>Here both observed and estimated covariances are converted into correlations and then we calculate the differences. Greater differences indicate problematic items.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(model2.fit, <span class="at">type=</span><span class="st">"cor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$type
[1] "cor.bollen"

$cov
       x1     x2     x3     x4     x5     x6
x1  0.000                                   
x2  0.000  0.000                            
x3  0.000  0.000  0.000                     
x4 -0.010  0.013  0.001  0.000              
x5 -0.010  0.015  0.000  0.967  0.000       
x6 -0.010  0.015 -0.002  0.968  0.000  0.000</code></pre>
</div>
</div>
</section>
<section id="standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals">Standardized residuals</h2>
<p>Here we standardize the covariance and in practice treat it as a z-score, values greater than 1.96 indicate problematic cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(model2.fit, <span class="at">type=</span><span class="st">"standardized"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$type
[1] "standardized"

$cov
       x1     x2     x3     x4     x5     x6
x1  0.000                                   
x2  0.000  0.000                            
x3 -1.636  1.394  0.000                     
x4 -1.342  1.533  0.108  0.000              
x5 -1.462  1.783  0.010 11.027  0.000       
x6 -1.347  1.868 -0.199 11.039  0.000  0.000</code></pre>
</div>
</div>
</section>
<section id="modification-indices" class="level2">
<h2 class="anchored" data-anchor-id="modification-indices">Modification Indices</h2>
<p>We should look at modification indices that give as an estimate change of our chi-square value if we make changes to our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationindices</span>(model2.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   lhs op rhs      mi    epc sepc.lv sepc.all sepc.nox
18  f2 =~  x1   1.522 -0.014  -0.013   -0.014   -0.014
19  f2 =~  x2   3.561  0.022   0.021    0.022    0.022
20  f2 =~  x3   0.117 -0.004  -0.004   -0.004   -0.004
21  f2 =~  x4 225.561  0.939   0.901    0.923    0.923
22  x1 ~~  x2   0.105  0.030   0.030    1.446    1.446
23  x1 ~~  x3   5.001 -0.204  -0.204   -9.753   -9.753
24  x1 ~~  x4   1.821 -0.015  -0.015   -0.109   -0.109
25  x1 ~~  x5   0.481 -0.002  -0.002   -0.043   -0.043
26  x1 ~~  x6   0.153  0.001   0.001    0.036    0.036
27  x2 ~~  x3   3.971  0.173   0.173    7.516    7.516
28  x2 ~~  x4   2.366  0.017   0.017    0.117    0.117
29  x2 ~~  x5   0.042  0.000   0.000   -0.012   -0.012
30  x2 ~~  x6   0.357  0.001   0.001    0.052    0.052
31  x3 ~~  x4   0.012  0.001   0.001    0.008    0.008
32  x3 ~~  x5   0.931  0.002   0.002    0.056    0.056
33  x3 ~~  x6   0.970 -0.002  -0.002   -0.085   -0.085
34  x4 ~~  x5   2.227  0.019   0.019    0.072    0.072
35  x4 ~~  x6   3.243  0.023   0.023    0.130    0.130</code></pre>
</div>
</div>
</section>
<section id="modifying-the-model" class="level2">
<h2 class="anchored" data-anchor-id="modifying-the-model">Modifying the model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="st">f1 =~ x1 + x2 + x3 </span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="st">f2 =~ x4 + x5 + x6</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>model2.<span class="fl">1.</span>fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model2<span class="fl">.1</span>, <span class="at">data =</span> df)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2.<span class="fl">1.</span>fit, <span class="at">standardized=</span><span class="cn">TRUE</span>, <span class="at">fit.measures=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 58 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        13

  Number of observations                           250

Model Test User Model:
                                                      
  Test statistic                                 7.569
  Degrees of freedom                                 8
  P-value (Chi-square)                           0.477

Model Test Baseline Model:

  Test statistic                              3202.055
  Degrees of freedom                                15
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.000

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -487.400
  Loglikelihood unrestricted model (H1)       -483.616
                                                      
  Akaike (AIC)                                1000.800
  Bayesian (BIC)                              1046.579
  Sample-size adjusted Bayesian (SABIC)       1005.368

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.072
  P-value H_0: RMSEA &lt;= 0.050                    0.817
  P-value H_0: RMSEA &gt;= 0.080                    0.025

Standardized Root Mean Square Residual:

  SRMR                                           0.007

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 =~                                                                 
    x1                1.000                               0.955    0.990
    x2                0.992    0.014   72.877    0.000    0.948    0.988
    x3                0.991    0.014   72.242    0.000    0.946    0.987
  f2 =~                                                                 
    x4                1.000                               0.963    0.986
    x5                1.024    0.015   66.812    0.000    0.986    0.988
    x6                0.997    0.014   69.570    0.000    0.960    0.990

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  f1 ~~                                                                 
    f2               -0.074    0.059   -1.263    0.206   -0.081   -0.081

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .x1                0.019    0.003    6.461    0.000    0.019    0.020
   .x2                0.023    0.003    7.286    0.000    0.023    0.025
   .x3                0.023    0.003    7.424    0.000    0.023    0.025
   .x4                0.027    0.004    7.763    0.000    0.027    0.029
   .x5                0.025    0.003    7.099    0.000    0.025    0.025
   .x6                0.019    0.003    6.260    0.000    0.019    0.020
    f1                0.912    0.083   10.951    0.000    1.000    1.000
    f2                0.927    0.085   10.858    0.000    1.000    1.000</code></pre>
</div>
</div>
</section>
<section id="let-us-see-if-the-residuals-tell-the-same-story" class="level2">
<h2 class="anchored" data-anchor-id="let-us-see-if-the-residuals-tell-the-same-story">Let us see if the residuals tell the same story</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(model2.<span class="fl">1.</span>fit, <span class="at">type=</span><span class="st">"standardized"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$type
[1] "standardized"

$cov
       x1     x2     x3     x4     x5     x6
x1  0.000                                   
x2  0.000  0.000                            
x3 -1.669  1.497  0.000                     
x4 -1.576  0.327 -0.624  0.000              
x5 -0.533  1.678  0.406  0.000  0.000       
x6 -0.907  1.477 -0.104 -0.684  0.861  0.000</code></pre>
</div>
</div>
</section>
<section id="what-about-modification-indices" class="level2">
<h2 class="anchored" data-anchor-id="what-about-modification-indices">What about modification indices</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationindices</span>(model2.<span class="fl">1.</span>fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   lhs op rhs    mi    epc sepc.lv sepc.all sepc.nox
16  f1 =~  x4 0.787 -0.012  -0.011   -0.011   -0.011
17  f1 =~  x5 0.439  0.008   0.008    0.008    0.008
18  f1 =~  x6 0.031  0.002   0.002    0.002    0.002
19  f2 =~  x1 2.236 -0.017  -0.017   -0.017   -0.017
20  f2 =~  x2 2.856  0.020   0.020    0.020    0.020
21  f2 =~  x3 0.016 -0.002  -0.001   -0.002   -0.002
22  x1 ~~  x2 0.016  0.017   0.017    0.839    0.839
23  x1 ~~  x3 2.856 -0.229  -0.229  -10.923  -10.923
24  x1 ~~  x4 0.031  0.000   0.000    0.016    0.016
25  x1 ~~  x5 0.476 -0.001  -0.001   -0.067   -0.067
26  x1 ~~  x6 0.051  0.000   0.000    0.023    0.023
27  x2 ~~  x3 2.236  0.192   0.192    8.386    8.386
28  x2 ~~  x4 1.923 -0.003  -0.003   -0.124   -0.124
29  x2 ~~  x5 0.174  0.001   0.001    0.039    0.039
30  x2 ~~  x6 1.393  0.002   0.002    0.116    0.116
31  x3 ~~  x4 1.090  0.002   0.002    0.093    0.093
32  x3 ~~  x5 0.189  0.001   0.001    0.040    0.040
33  x3 ~~  x6 1.946 -0.003  -0.003   -0.136   -0.136
34  x4 ~~  x5 0.031 -0.024  -0.024   -0.941   -0.941
35  x4 ~~  x6 0.439 -0.093  -0.093   -4.050   -4.050
36  x5 ~~  x6 0.787  0.133   0.133    6.150    6.150</code></pre>
</div>
</div>
</section>
<section id="exercise" class="level2">
<h2 class="anchored" data-anchor-id="exercise">Exercise</h2>
<p>Let us try a different model now. Go onto your posit cloud account and open the Week 5 project, follow the instructions and carry out the required CFA.</p>


</section>

</main> <!-- /main -->

<script>
  // htmlwidgets need to know to resize themselves when slides are shown/hidden.
  // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
  // slide changes (different for each slide format).
  (function () {
    // dispatch for htmlwidgets
    function fireSlideEnter() {
      const event = window.document.createEvent("Event");
      event.initEvent("slideenter", true, true);
      window.document.dispatchEvent(event);
    }

    function fireSlideChanged(previousSlide, currentSlide) {
      fireSlideEnter();

      // dispatch for shiny
      if (window.jQuery) {
        if (previousSlide) {
          window.jQuery(previousSlide).trigger("hidden");
        }
        if (currentSlide) {
          window.jQuery(currentSlide).trigger("shown");
        }
      }
    }

    // hookup for slidy
    if (window.w3c_slidy) {
      window.w3c_slidy.add_observer(function (slide_num) {
        // slide_num starts at position 1
        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
      });
    }

  })();
</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>