<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr Lazaros Gonidis">
<meta name="dcterms.date" content="2024-01-27">

<title>AdvancedStatistics - Introduction to Advanced Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">AdvancedStatistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Introduction to Advanced Statistics</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Dr Lazaros Gonidis </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 27, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="who-i-am" class="level2">
<h2 class="anchored" data-anchor-id="who-i-am">Who I am</h2>
<div class="columns">
<div class="column" style="width:20%;">
<p><img src="images/me.jpg" class="img-fluid" width="156"></p>
<p><img src="images/photo2.jpg" class="img-fluid" width="152"></p>
<p><img src="images/photo3.jpg" class="img-fluid" width="151"></p>
</div><div class="column" style="width:80%;">
<ol type="1">
<li>This is me (used to be)</li>
<li>I love my two boys</li>
<li>I also love computer games, motorbikes, music, food</li>
<li>Funnily enough I love maths and statistics, and even more teaching these</li>
<li>I am also dyslexic so please do tell me when you spot typing mistakes, usually whole words missing.</li>
</ol>
</div>
</div>
</section>
<section id="who-you-are" class="level2">
<h2 class="anchored" data-anchor-id="who-you-are">Who you are</h2>
<p>I have no idea who you are but I hope by the end of this module you will love statistics a bit more and you will appreciate even more why they are paramount for Psychological research.</p>
</section>
<section id="todays-aims-in-terms-of-the-module" class="level2">
<h2 class="anchored" data-anchor-id="todays-aims-in-terms-of-the-module">Today’s Aims in Terms of the Module</h2>
<ol type="1">
<li>Canvas</li>
<li>Rstudio/Posit</li>
<li>discord</li>
<li>Assessment</li>
<li>Quizzes (Badges to be confirmed)</li>
<li>Github</li>
</ol>
</section>
<section id="canvas" class="level2">
<h2 class="anchored" data-anchor-id="canvas">Canvas</h2>
<p>Hopefully you should know where to find our Canvas website, but just in case:</p>
<p><a href="https://canvas.sussex.ac.uk/courses/26315/pages/module-home-page" class="uri">https://canvas.sussex.ac.uk/courses/26315/pages/module-home-page</a></p>
</section>
<section id="rstudioposit-cloud" class="level2">
<h2 class="anchored" data-anchor-id="rstudioposit-cloud">RStudio/Posit Cloud</h2>
<p>For our analysis we will be using exclusively R and mainly Posit Cloud. However, I strongly believe that as future scientists you should also have locally installed RStudio/Posit, have it up to date and use that for your everyday work. I would also advise you to attend our workshops bringing your own laptops/tablets/mobile phones.</p>
<p>You can join our Posit Cloud Workspace by following this link:</p>
<p><a href="https://posit.cloud/spaces/469376/join?access_code=4YBUfhrNPGU2oWWw5Zym6bepaVV6izQ8O1KE6THK" class="uri">https://posit.cloud/spaces/469376/join?access_code=4YBUfhrNPGU2oWWw5Zym6bepaVV6izQ8O1KE6THK</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../..\qr-code.png" class="img-fluid figure-img" width="336"></p>
</figure>
</div>
</section>
<section id="discord-as-our-mean-of-day-to-day-communication" class="level2">
<h2 class="anchored" data-anchor-id="discord-as-our-mean-of-day-to-day-communication">Discord as our mean of day to day communication</h2>
<p>We will be using discord as our main communication channel, please use it for any stats related questions. If you have any more sensitive questions please do not hesitate to email me at: L.Gonidis@Sussex.ac.uk</p>
<p>You can join us by following this link: <a href="https://discord.gg/9TV3xzMZ" class="uri">https://discord.gg/9TV3xzMZ</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../..\wr-code2.png" class="img-fluid figure-img" width="345"></p>
</figure>
</div>
</section>
<section id="assessment" class="level2">
<h2 class="anchored" data-anchor-id="assessment">Assessment</h2>
<p>The module will be assessed exclusively by coursework. This will be in the form of three 1,000 words results sections. The deadlines are:</p>
<ol type="1">
<li>Report 1, February 13th 16:00</li>
<li>Report 2, March 14th 16:00</li>
<li>Report 3, April 23rd 16:00</li>
</ol>
<p>All submissions will be via Canvas submission points in the Assignments, Contributory E-Submission subsection. Each report topic will be released in our workshop the week prior to the submission deadline. Specifically, for Report 1 the topic will be Mediation/Moderation analysis using lavaan. You will receive detailed instructions on that next Monday.</p>
</section>
<section id="quizzes-and-badgeshopefully" class="level2">
<h2 class="anchored" data-anchor-id="quizzes-and-badgeshopefully">Quizzes and Badges(hopefully)</h2>
<p>Every week there will be a Canvas quiz provided so you can practice and enhance your understanding. These are absolutely non-compulsory but do spend some time trying to complete them. You will also be collecting points while you complete these (and other Canvas activities) and at the end of the module the two students with the highest scores will receive a surprise present.</p>
</section>
<section id="github" class="level2">
<h2 class="anchored" data-anchor-id="github">Github</h2>
<p>Github has been increasingly becoming a standard in the world of coding and statistical analysis as it can serve both as a repository and a host of websites related to projects. We will have a very brief demonstration today and we will return next week and start using it as a standard in our module.</p>
</section>
<section id="essential-and-supplamentary-materials" class="level2">
<h2 class="anchored" data-anchor-id="essential-and-supplamentary-materials">Essential and Supplamentary Materials</h2>
<div class="columns">
<div class="column" style="width:20%;">
<p><img src="../..\kline.JPG" class="img-fluid" width="130"></p>
<p><img src="../..\Newsom.JPG" class="img-fluid" width="129"></p>
</div><div class="column" style="width:80%;">
<ol type="1">
<li><p><a href="https://ebookcentral.proquest.com/lib/suss/reader.action?docID=4000663">Principles and Practice of Structural Equation Modeling</a></p></li>
<li><p><a href="Longitudinal Structural Equation Modeling: A comprehensive Introduction">Longitudinal Structural Equation Modeling: A comprehensive Introduction</a></p></li>
<li><p><a href="https://lavaan.ugent.be/tutorial/">Official lavaan tutorial from lavaan.org</a></p></li>
<li><p><a href="https://bookdown.org/annabrown/psychometricsR/">Psychometrics in Exercises using R and Rstudio</a> by Prof Anna Brown</p></li>
<li><p><a href="https://stats.oarc.ucla.edu/r/seminars/rsem/#s1a">Introduction to Structural Equation Modeling (SEM) in R with lavaan</a> by Dr Johnny Lin</p>
<p>** And many other online resources that will be revealed in due time</p></li>
</ol>
</div>
</div>
</section>
<section id="todays-aims-in-terms-of-structural-equation-modeling-sem" class="level2">
<h2 class="anchored" data-anchor-id="todays-aims-in-terms-of-structural-equation-modeling-sem">Today’s Aims in Terms of Structural Equation Modeling (SEM)</h2>
<ol type="1">
<li>Introduce key terminology that we will be using this term</li>
<li>Discuss examples of <strong>simple and multiple regression</strong></li>
<li>Revisit the same examples using <strong>lavaan</strong></li>
<li>Discuss <strong>baximum likelihood</strong> vs.&nbsp;<strong>least squares</strong></li>
</ol>
</section>
<section id="key-terminology" class="level2">
<h2 class="anchored" data-anchor-id="key-terminology">Key Terminology</h2>
<p>We will be using quite a few terms in our module so it is important to define them in advance and try to use them consistently. Most of the them are used as in the field but you could come across some slight variations in terminology. This should not put you off or scare you, as long as you understand the substance of each term. It is also a good idea to try to learn the visual equivalents of these terms</p>
</section>
<section id="key-terminology-2" class="level2">
<h2 class="anchored" data-anchor-id="key-terminology-2">Key Terminology 2</h2>
<div class="columns">
<div class="column" style="width:20%;">
<p><img src="../..\path.JPG" width="164" height="438"></p>
</div><div class="column" style="width:80%;">
<ol type="1">
<li><strong>latent variable:</strong> a variable that is constructed/inferred indirectly by the data and does not exist in the data.</li>
<li><strong>observed variable:</strong> a variable that has been measured and exists in our data.</li>
<li><strong>exogenous variable:</strong> an independent variable that explains an endogenous variable. Can be either observed <span class="math inline">\((x)\)</span> or latent <span class="math inline">\((ξ)\)</span>.</li>
<li><strong>endogenous variable:</strong> a dependent variable that has a causal path leading to it. Can be either observed <span class="math inline">\((y)\)</span> or latent <span class="math inline">\((η)\)</span>.</li>
<li><strong>measurement model:</strong> a model that links observed variables with latent variables</li>
</ol>
</div>
</div>
</section>
<section id="key-terminology-3" class="level2">
<h2 class="anchored" data-anchor-id="key-terminology-3">Key Terminology 3</h2>
<div class="columns">
<div class="column" style="width:20%;">
<p><img src="../..\path.JPG" width="164" height="438"></p>
</div><div class="column" style="width:80%;">
<ol start="6" type="1">
<li><strong>indicator:</strong> an observed variable in a measurement model (can be exogenous or endogenous).</li>
<li><strong>factor</strong>: a latent variable defined by its indicators (can be exogenous or endogenous).</li>
<li><strong>loading:</strong> a path between an indicator and a factor.</li>
<li><strong>structural model:</strong> a model that specifies causal relationships among exogenous variables to endogenous variables (can be observed or latent).</li>
<li><strong>regression path:</strong> a path between exogenous and endogenous variables (can be observed or latent).</li>
</ol>
</div>
</div>
</section>
<section id="are-you-ready-for-the-first-headache-question" class="level2">
<h2 class="anchored" data-anchor-id="are-you-ready-for-the-first-headache-question">Are you ready for the first headache question?</h2>
<p>So far, in linear regression we have learnt that <span class="math inline">\(x\)</span> is an <strong>independent</strong> variable and <span class="math inline">\(y\)</span> the <strong>dependent</strong> variable or outcome. However, in measurement models, the use of <span class="math inline">\(x\)</span> or <span class="math inline">\(y\)</span> depends on the type of factor we are referring to. If an indicator depends on an <strong>exogenous</strong> factor, the we refer to it as <span class="math inline">\(x\)</span>-side. If an indicator depends on an <strong>endogenous</strong> factor then we refer to it as <span class="math inline">\(y\)</span>-side.</p>
</section>
<section id="let-us-expand-on-this-headache-a-bit-more" class="level2">
<h2 class="anchored" data-anchor-id="let-us-expand-on-this-headache-a-bit-more">Let us expand on this headache a bit more</h2>
<p><img src="../..\path2.JPG" class="img-fluid"></p>
</section>
<section id="simple-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-regression">Simple Regression</h2>
<p>So far we have learnt that a simple regression is the linear relation between a predictor (or an independent variable, or an observed exogenous variable) and an outcome (or observed endogenous variable).</p>
<p><span class="math display">\[
y_1 = b_0 +b_1x_1 + ε_1
\]</span></p>
<p>where&nbsp;<span class="math inline">\(b_0\)</span> is the intercept and <span class="math inline">\(b_1\)</span> is the coefficient of&nbsp;<span class="math inline">\(x_1\)</span> (observed predictor) and&nbsp;<span class="math inline">\(ε_1\)</span> is the residual with <span class="math inline">\(y_1\)</span> being the outcome.</p>
</section>
<section id="simple-regression-cont." class="level2">
<h2 class="anchored" data-anchor-id="simple-regression-cont.">Simple Regression cont.</h2>
<p><strong>I strongly recommend reading Kline chapter 2, pages 25-30 at minimum, Regression Fundamentals.</strong></p>
<p><span class="math display">\[
\hat{Y} = B_XX + A_X
\]</span></p>
<p>The above equation represents <strong>predicting Y from X</strong></p>
<p>Also referred to as <strong>regressing Y on X</strong>, with <span class="math inline">\(\hat{Y}\)</span> representing <strong>predicted scores</strong>, <span class="math inline">\(B_X\)</span> unstandardised regression coefficient for predictor <span class="math inline">\(X\)</span>, also known as slope, and <span class="math inline">\(A_X\)</span> is the intercept.</p>
<p>Generally, with linear models we would use <strong>ordinary least square</strong> (OLS) so that the <strong>least squares criterion</strong> is satisfied. In practice, we are trying to minimise the sum of squared residuals, <span class="math inline">\(\sum(Y-\hat{Y})\)</span></p>
</section>
<section id="let-us-see-an-example-with-data" class="level2">
<h2 class="anchored" data-anchor-id="let-us-see-an-example-with-data">Let us see an example with data</h2>
<p>We will work with the randomly generated data included in the <strong>random.csv</strong></p>
<p>The datafile includes three variables:</p>
<p><strong>reading: reading ability as assessed in school</strong></p>
<p><strong>income: weekly family income in £</strong></p>
<p><strong>books: number of books read in a month (on average)</strong></p>
<p>We will create a simple regression model of <strong>reading</strong> &nbsp;regressing on <strong>income</strong> using <strong>lm()</strong></p>
</section>
<section id="loading-the-datafile" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-datafile">Loading the datafile</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"random.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-the-model-and-getting-model-parameters" class="level2">
<h2 class="anchored" data-anchor-id="creating-the-model-and-getting-model-parameters">Creating the model and getting model parameters</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>reading_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(reading <span class="sc">~</span> income, <span class="at">data =</span> df)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the option below instructs R to give us the output in non-exponential notation</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reading_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = reading ~ income, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-50.590 -16.562  -0.178  13.429  48.207 

Coefficients:
             Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept) 188.17787    6.68278  28.159 &lt; 0.0000000000000002 ***
income        0.11800    0.01662   7.098       0.000000000201 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.44 on 98 degrees of freedom
Multiple R-squared:  0.3395,    Adjusted R-squared:  0.3328 
F-statistic: 50.38 on 1 and 98 DF,  p-value: 0.0000000002013</code></pre>
</div>
</div>
</section>
<section id="looking-at-the-output" class="level2">
<h2 class="anchored" data-anchor-id="looking-at-the-output">Looking at the output</h2>
<p>Our intercept is 188.18 and our income coefficient is 0.118 (0.12). This means that the reading ability of a student with a family income of £0 will be 188.18 and for every £1 of family income increase the reading ability will increase by 0.12.</p>
<p>We also see <strong>residual standard error of 21.44</strong></p>
<p>The <strong>square of that value is 459.67</strong></p>
</section>
<section id="let-us-recreate-the-same-model-using-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="let-us-recreate-the-same-model-using-lavaan">Let us recreate the same model using Lavaan</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lavaan uses a simple language when specifying the model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#simple regression using lavaan </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reading_lav <span class="ot">&lt;-</span>   <span class="st">'</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="st">  # regressions</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="st">    reading ~ 1 + income</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="st">  # variance (optional)</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="st">    income ~~ income</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>reading_lav_sem <span class="ot">&lt;-</span> <span class="fu">sem</span>(reading_lav, <span class="at">data=</span>df)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reading_lav_sem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 11 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         5

  Number of observations                           100

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
  reading ~                                            
    income             0.118    0.016    7.170    0.000

Intercepts:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
   .reading          188.178    6.616   28.445    0.000
    income           380.752   12.896   29.525    0.000

Variances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
    income         16630.573 2351.918    7.071    0.000
   .reading          450.401   63.696    7.071    0.000</code></pre>
</div>
</div>
</section>
<section id="comparing-the-two-outputs" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-two-outputs">Comparing the two outputs</h2>
<p>We observe that the estimates of the regression coefficients are the same despite <strong>lm()</strong> using <strong>least squares (LS)</strong> and <strong>lavaan</strong> using <strong>maximum likelihood (ML)</strong>. However the variances are different with <strong>459.67</strong> for <strong>lm()</strong> and <strong>450.40</strong> for <strong>lavaan.</strong></p>
<p>In we want to convert from <strong>LS variance to ML variance</strong> we can use the following formula</p>
<p><span class="math display">\[
\hat{σ}_{ML}^2 = \frac{(N-k)}{n}\hat{σ}_{LS}^2
\]</span></p>
<p>Where <span class="math inline">\(N\)</span> and <span class="math inline">\(n\)</span> are the sample sizes and <span class="math inline">\(k\)</span> is the number or parameters to estimate, in this case <span class="math inline">\(k\)</span>=2, one intercept and one regression coefficient</p>
<p><span class="math display">\[
\hat{σ}_{ML}^2 = \frac{(100-2)}{100}21.44^2=450.48
\]</span></p>
</section>
<section id="visualising-with-sempaths-from-semplot" class="level2">
<h2 class="anchored" data-anchor-id="visualising-with-sempaths-from-semplot">Visualising with semPaths() from semPlot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(reading_lav_sem,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">"circle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-revealjs/unnamed-chunk-4-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="ols-vs-ml" class="level2">
<h2 class="anchored" data-anchor-id="ols-vs-ml">OLS vs ML</h2>
<p>Generally in SEM, we use the <strong>maximum likelihood estimator (MLE)</strong>. In this module we will be using the acronyms <strong>ML</strong> and <strong>MLE</strong>&nbsp;to denote the maximum likelihood estimator method. This method estimates model parameters by maximising the likelihood function. In other words, maximising the probability of observing our existing data points given specific parameter values. We will be discussing in details what these parameters are in SEM (e.g., coefficients, latent variable variances, etc.). It should also be noted that <strong>MLE</strong> is not the only estimation methods, other methods can also be successfully implemented, such as <strong>generalised least squares</strong>. We decided on the appropriate estimator based on our data characteristics and assumptions.</p>
</section>
<section id="multiple-regression-lm" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-lm">Multiple regression, lm()</h2>
<p>We can expand the previous example to now include a second predictor, <strong>books</strong> which represents the number of books read in a month (on average)</p>
<p><span class="math display">\[
y_1 = b_0 +b_1x_1 + b_2x_2 + ε_1
\]</span></p>
<p>You may also come across the following notation:</p>
<p><span class="math display">\[
\hat{Y} = B_XX + +B_WW + A_{X,W}
\]</span></p>
<p>Important to note here that <span class="math inline">\(B_X\)</span> and <span class="math inline">\(B_W\)</span> are the <strong>unstandardized partial regression coefficients</strong>, <span class="math inline">\(A_{X,W}\)</span> is the intercept. For more information please read Kline page 30.</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<p>Multiple regression, lm()</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reading2_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(reading <span class="sc">~</span> income <span class="sc">+</span> books, <span class="at">data =</span> df)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reading2_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = reading ~ income + books, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-50.397 -13.633   0.547  13.698  51.585 

Coefficients:
             Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept) 187.28030    6.14063  30.499 &lt; 0.0000000000000002 ***
income        0.06160    0.01997   3.085              0.00265 ** 
books         6.14601    1.40272   4.382            0.0000298 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.69 on 97 degrees of freedom
Multiple R-squared:  0.4487,    Adjusted R-squared:  0.4373 
F-statistic: 39.47 on 2 and 97 DF,  p-value: 0.0000000000002875</code></pre>
</div>
</div>
</section>
<section id="multiple-regression-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-lavaan">Multiple regression, lavaan</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>reading2_lav <span class="ot">&lt;-</span>   <span class="st">'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # regressions</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="st">    reading ~ 1 + income + books</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="st">  # covariance</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="st">    income ~~ books</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>reading2_lav_sem <span class="ot">&lt;-</span> <span class="fu">sem</span>(reading2_lav, <span class="at">data=</span>df)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reading2_lav_sem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 38 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         9

  Number of observations                           100

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
  reading ~                                            
    income             0.062    0.020    3.132    0.002
    books              6.146    1.382    4.449    0.000

Covariances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
  income ~~                                            
    books            152.610   28.168    5.418    0.000

Intercepts:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
   .reading          187.280    6.048   30.967    0.000
    income           380.752   12.896   29.525    0.000
    books              3.640    0.184   19.827    0.000

Variances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
   .reading          375.988   53.173    7.071    0.000
    income         16630.574 2351.918    7.071    0.000
    books              3.370    0.477    7.071    0.000</code></pre>
</div>
</div>
</section>
<section id="visualising-with-sempaths-from-semplot-1" class="level2">
<h2 class="anchored" data-anchor-id="visualising-with-sempaths-from-semplot-1">Visualising with semPaths() from semPlot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(reading2_lav_sem,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">"spring"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-revealjs/unnamed-chunk-7-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="visualising-with-sempaths-from-semplot-2" class="level2">
<h2 class="anchored" data-anchor-id="visualising-with-sempaths-from-semplot-2">Visualising with semPaths() from semPlot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(reading2_lav_sem,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,          </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,          </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">"tree"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-revealjs/unnamed-chunk-8-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="a-prelude-to-next-week.-mediation-with-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="a-prelude-to-next-week.-mediation-with-lavaan">A prelude to next week. Mediation with Lavaan</h2>
<p>We will explore whether the number of <strong>books</strong> read actually <strong>mediate</strong> the effect of <strong>income</strong> on <strong>reading</strong> ability. We will not go in depth today as we will discuss this topic next week in detail. We will just demonstrate how the code would change in lavaan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>reading_med_model <span class="ot">&lt;-</span> <span class="st">' # direct effect</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="st">             reading ~ c*income</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">           # mediator</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">             books ~ a*income</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">             reading ~ b*books</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="st">           # indirect effect (a*b)</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">             ab := a*b</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">           # total effect</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">             total := c + (a*b)</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="st">         '</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>reading_med <span class="ot">&lt;-</span> <span class="fu">sem</span>(reading_med_model, <span class="at">data =</span> df)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reading_med )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         5

  Number of observations                           100

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
  reading ~                                            
    income     (c)     0.062    0.020    3.132    0.002
  books ~                                              
    income     (a)     0.009    0.001    8.431    0.000
  reading ~                                            
    books      (b)     6.146    1.382    4.449    0.000

Variances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
   .reading          375.988   53.173    7.071    0.000
   .books              1.970    0.279    7.071    0.000

Defined Parameters:
                   Estimate   Std.Err  z-value  P(&gt;|z|)
    ab                 0.056    0.014    3.935    0.000
    total              0.118    0.016    7.170    0.000</code></pre>
</div>
</div>
</section>
<section id="let-us-visualise-the-above-model" class="level2">
<h2 class="anchored" data-anchor-id="let-us-visualise-the-above-model">Let us visualise the above model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(reading_med,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,          </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,          </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">"tree"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">rotation =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-revealjs/unnamed-chunk-10-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="to-conclude" class="level2">
<h2 class="anchored" data-anchor-id="to-conclude">To conclude</h2>
<p>Hopefully, this was a gentle introduction to the module and lavaan. We will be following a more formal approach in the coming weeks. In the meantime do spend some time this week to do the suggested reading and practice with R and lavaan in our Posit Cloud Workspace.</p>


</section>

</main> <!-- /main -->

<script>
  // htmlwidgets need to know to resize themselves when slides are shown/hidden.
  // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
  // slide changes (different for each slide format).
  (function () {
    // dispatch for htmlwidgets
    function fireSlideEnter() {
      const event = window.document.createEvent("Event");
      event.initEvent("slideenter", true, true);
      window.document.dispatchEvent(event);
    }

    function fireSlideChanged(previousSlide, currentSlide) {
      fireSlideEnter();

      // dispatch for shiny
      if (window.jQuery) {
        if (previousSlide) {
          window.jQuery(previousSlide).trigger("hidden");
        }
        if (currentSlide) {
          window.jQuery(currentSlide).trigger("shown");
        }
      }
    }

    // hookup for slidy
    if (window.w3c_slidy) {
      window.w3c_slidy.add_observer(function (slide_num) {
        // slide_num starts at position 1
        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
      });
    }

  })();
</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>